### ISSUE TITLE
Make language / usage more platform agnostic 

### ISSUE THREAD

**Issue by plantainrain** [apostrophecms/apostrophe-open-graph#6]
A lot of the language explicitly uses `Facebook` but it covers other platforms as well. Should this be adjusted? Some users are confused that it only covers Facebook use cases.

**Comment by boutell** [comment]
In the documentation, you mean? Yeah definitely say "Facebook, LinkedIn, and other platforms that support Open Graph."

**Comment by plantainrain** [comment]
@boutell more so in the help text and tab labels etc. 

![screen shot 2018-04-19 at 10 47 26 am](https://user-images.githubusercontent.com/7018825/38999130-1a0ade24-43bf-11e8-84b4-788623b6a607.png)

**Comment by austinstarin** [comment]
@mtthwmnc That could be easily changed, do you want to make a PR?
